services:
  backend:
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/backend:/app
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/workspace
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    working_dir: /app
    env_file:
      - .env
    ports:
      - "${HOST_PORT_FRONTEND:-3000}:3000"
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/frontend:/app
      - /app/node_modules
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/workspace
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"