"""add nickname column

Revision ID: 2ac5599a1353
Revises: 0164fe70099c
Create Date: 2026-06-10 07:57:50.899226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac5599a1353'
down_revision: Union[str, Sequence[str], None] = '0164fe70099c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.execute("UPDATE users SET nickname = 'User' || id")
    op.alter_column('users', 'nickname', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
