"""add_is_developer_to_user

Revision ID: 43cc1106cb5a
Revises: 0164fe70099c
Create Date: 2026-05-29 04:43:41.008828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cc1106cb5a'
down_revision: Union[str, Sequence[str], None] = '0164fe70099c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Tạo cột is_developer với nullable=True trước để không làm lỗi User cũ
    op.add_column('users', sa.Column('is_developer', sa.Boolean(), nullable=True))
    
    # 2. Cập nhật tất cả bản ghi cũ thành False để đảm bảo dữ liệu nhất quán trước khi chuyển sang nullable=False
    op.execute("UPDATE users SET is_developer = False WHERE is_developer IS NULL")
    
    # 3. Sau khi dữ liệu cũ đã an toàn, chuyển cột này thành nullable=False theo đúng chuẩn
    op.alter_column('users', 'is_developer',
               existing_type=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_developer')
    # ### end Alembic commands ###
