services:
  workspace:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - .:/workspace:cached
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db-postgre:5432/${POSTGRES_DB:-web_base}
    command: sleep infinity
    depends_on:
      - db-postgre
      - backend
      - frontend
